# Finno-Ugric Dataset: Category Visualizations

This notebook loads the CSV files in this folder and visualizes the most frequent categories in each dataset.

In [15]:
from pathlib import Path
import pandas as pd
from IPython.display import HTML, display

try:
    import plotly.express as px
except ImportError:
    import sys
    import subprocess
    subprocess.check_call([sys.executable, '-m', 'pip', 'install', 'plotly'])
    import plotly.express as px

pd.set_option('display.max_columns', 100)
pd.set_option('display.width', 140)

In [16]:
data_dir = Path('.')

files = {
    'places': 'finno-ugric-object-places.csv',
    'materials': 'finno-ugric-object-materials.csv',
    'collectors': 'finno-ugric-object-collectors.csv',
    'relations': 'finno_ugric_object_relations.csv',
    'objects_sheet': 'finno-ugric-objects-dataset.xlsx - Sheet1.csv'
}

dfs = {}
for name, filename in files.items():
    path = data_dir / filename
    if path.exists():
        dfs[name] = pd.read_csv(path)

print('Loaded tables:')
for name, df in dfs.items():
    print(f'- {name}: {df.shape[0]:,} rows x {df.shape[1]} columns')

Loaded tables:
- places: 14,621 rows x 13 columns
- materials: 15,178 rows x 3 columns
- collectors: 16,238 rows x 4 columns
- relations: 889 rows x 9 columns
- objects_sheet: 10,079 rows x 28 columns

In [17]:
summary = []
for name, df in dfs.items():
    summary.append({
        'table': name,
        'rows': df.shape[0],
        'columns': df.shape[1],
        'categorical_columns': ', '.join(df.select_dtypes(include=['object']).columns.tolist())
    })

pd.DataFrame(summary).sort_values('table').reset_index(drop=True)

           table   rows  columns                                categorical_columns
0     collectors  16238        4                    collector, collector_normalized
1      materials  15178        3                        material, material_category
2  objects_sheet  10079       28  museal_number, image_url, object_url, title, e...
3         places  14621       13  place_norm, country, region, district, Distric...
4      relations    889        9                                        relation_id

## Category Plot Helper

The function below draws interactive top-N category charts.
Hover over any bar to see the exact count.
A table of the same graph values is shown before each chart.

In [21]:
def plot_top_categories(df, table_name, columns, top_n=15):
    valid_cols = [c for c in columns if c in df.columns]
    if not valid_cols:
        print(f'No requested categorical columns found in: {table_name}')
        return

    for col in valid_cols:
        counts = (
            df[col]
            .astype('string')
            .str.strip()
            .replace({'': pd.NA})
            .dropna()
            .value_counts()
            .head(top_n)
        )

        if counts.empty:
            print(f'No non-null values in {table_name}.{col}')
            continue

        table_df = counts.reset_index()
        table_df.columns = ['category', 'count']

        print(f"Top {min(top_n, len(table_df))} values for {table_name}.{col}")
        display(table_df)

        plot_df = table_df.sort_values('count', ascending=True)

        fig = px.bar(
            plot_df,
            x='count',
            y='category',
            orientation='h',
            title=f"{table_name} - Top {min(top_n, len(plot_df))} values in {col}",
            labels={'count': 'Count', 'category': col}
        )

        fig.update_traces(
            hovertemplate=f"{col}: %{{y}}<br>Count: %{{x}}<extra></extra>"
        )
        fig.update_layout(height=max(420, 28 * len(plot_df) + 180))

        # Render as HTML to avoid renderer dependency issues in some kernels.
        display(HTML(fig.to_html(include_plotlyjs='cdn', full_html=False)))

In [22]:
recommended_category_columns = {
    'places': ['country', 'region', 'district', 'local_admin', 'settlement', 'coords_source'],
    'materials': ['material_category', 'material'],
    'collectors': ['collector_normalized', 'collector'],
    'relations': ['relation_id'],
    'objects_sheet': []
}

for table_name, df in dfs.items():
    cols = recommended_category_columns.get(table_name, [])

    # Fallback: use all object columns except likely ID fields if no explicit list is provided.
    if not cols:
        cols = [
            c for c in df.select_dtypes(include=['object']).columns
            if 'id' not in c.lower()
        ][:6]

    print(f'\n=== {table_name} ===')
    plot_top_categories(df, table_name, cols, top_n=15)

=== places ===
Top 10 values for places.country

   category  count
0   Venemaa  12805
1      Läti    677
2   Ukraina    234
3     Soome    213
4    Ungari     70
5       NSV     51
6    Rootsi     41
7   Moldova      1
8  Rumeenia      1
9  Komi NSV      1

Top 15 values for places.region

                 category  count
0       Leningradi oblast   2396
1               Mari ANSV   1702
2            Udmurdi ANSV   1679
3             Mordva ANSV    978
4          Tjumeni oblast    922
5           Kirovi oblast    770
6             Tatari ANSV    532
7            Karjala ANSV    461
8               Komi ANSV    443
9          Vologda oblast    352
10          Komi Vabariik    298
11         Bashkiiri ANSV    287
12         Handi-Mansi RR    270
13          Bashkiri ANSV    244
14  Taga-Karpaatia oblast    207

Top 15 values for places.district

                category  count
0      Kingissepa rajoon   1114
1           Morki rajoon    572
2   Boksitogorski rajoon    504
3       Berjozovo rajoon    399
4         Tihvini rajoon    381
5       Zavjalovo rajoon    377
6        Babajevo rajoon    337
7      Ust-Kulomi rajoon    320
8         Surguti rajoon    288
9           Talsi rajoon    282
10         Agrõzi rajoon    257
11        Glazovi rajoon    248
12    Mari-Tureki rajoon    237
13           Kezi rajoon    224
14     Ventspilsi rajoon    220

Top 15 values for places.local_admin

                  category  count
0                Arino k/n    393
1         Aleksejevski k/n    231
2      Soikino külanõukogu     92
3        Kuija külanõukogu     90
4     Kuratovo külanõukogu     69
5     Sidorovo külanõukogu     56
6     Krakolje külanõukogu     53
7        Arino külanõukogu     41
8        Agani külanõukogu     35
9   Radogoštši külanõukogu     30
10               Parzi k/n     30
11       Uguti külanõukogu     30
12       Kolka külanõukogu     27
13  Semisolani külanõukogu     25
14     Vistino külanõukogu     25

Top 15 values for places.settlement

                  category  count
0             Vistino küla    282
1            Sabajevo küla    142
2       Varklet-Bodja küla    131
3             Lobaski küla    118
4              Samaara kub    110
5          Povodimovo küla    109
6           Vjatka-Poljana    101
7         Mihhailovka küla    101
8                Alnashshi     99
9                 Malmõzhi     97
10           Kosmodemjansk     97
11             Glinki küla     84
12           Koštrõgi küla     82
13  Mordovski Pimburi küla     81
14             Tshavainuri     79

Top 4 values for places.coords_source

                    category  count
0       same_district_region    461
1           same_place_exact    268
2  same_place_no_local_admin     42
3               original_row     38

=== materials ===
Top 12 values for materials.material_category

         category  count
0            puit   6353
1        tekstiil   5426
2          metall   1619
3            nahk    743
4       keraamika    245
5           klaas    146
6             luu    129
7         plastik     99
8           kivim     57
9           paber     28
10  plast, metall     14
11           toit      2

Top 15 values for materials.material

      category  count
0         kask   1181
1      puuvill    656
2         puit    637
3         raud    632
4        kuusk    601
5       metall    522
6         lina    500
7         toht    479
8         nahk    402
9      villane    395
10      linane    373
11  puuvillane    366
12        mänd    341
13    lehtpuit    312
14        vill    312

=== collectors ===
Top 15 values for collectors.collector_normalized

            category  count
0   Aleksei Peterson   2845
1          Mare Piho    979
2        Lembit Lepp    972
3          Heno Sarv    918
4         Edgar Saar    906
5      Marika Mikkor    840
6       Priit Härmas    461
7       Aado Lintrop    433
8        Heiki Pärdi    425
9    Aleksander Põrk    353
10         Aldo Luud    337
11       Jüri Linnus    301
12         Jüri Karm    295
13         Art Leete    239
14       Ülo Maaring    239

Top 15 values for collectors.collector

            category  count
0   Aleksei Peterson   2796
1          Mare Piho    979
2        Lembit Lepp    925
3          Heno Sarv    910
4         Edgar Saar    827
5      Marika Mikkor    764
6       Priit Härmas    446
7       Aado Lintrop    422
8        Heiki Pärdi    412
9    Aleksander Põrk    353
10         Aldo Luud    321
11       Jüri Linnus    301
12         Jüri Karm    293
13        Uuno Ojala    239
14       Ülo Maaring    239

=== relations ===
Top 15 values for relations.relation_id

     category  count
0   rel_00001      1
1   rel_00598      1
2   rel_00587      1
3   rel_00588      1
4   rel_00589      1
5   rel_00590      1
6   rel_00591      1
7   rel_00592      1
8   rel_00593      1
9   rel_00594      1
10  rel_00595      1
11  rel_00596      1
12  rel_00597      1
13  rel_00599      1
14  rel_00585      1

=== objects_sheet ===
Top 15 values for objects_sheet.museal_number

           category  count
0       ERM B 225:9      1
1      ERM B 114:54      1
2      ERM B 114:47      1
3      ERM B 114:48      1
4      ERM B 114:49      1
5      ERM B 114:50      1
6      ERM B 114:51      1
7      ERM B 114:52      1
8      ERM B 114:53      1
9      ERM B 114:55      1
10     ERM B 114:45      1
11     ERM B 114:56      1
12  ERM B 114:57/ab      1
13     ERM B 114:58      1
14     ERM B 114:59      1

Top 15 values for objects_sheet.image_url

                                     category  count
0   http://opendata.muis.ee/media-list/518063      1
1   http://opendata.muis.ee/media-list/621211      1
2   http://opendata.muis.ee/media-list/621203      1
3   http://opendata.muis.ee/media-list/621204      1
4   http://opendata.muis.ee/media-list/621206      1
5   http://opendata.muis.ee/media-list/621207      1
6   http://opendata.muis.ee/media-list/621208      1
7   http://opendata.muis.ee/media-list/621209      1
8   http://opendata.muis.ee/media-list/621210      1
9   http://opendata.muis.ee/media-list/621212      1
10  http://opendata.muis.ee/media-list/621201      1
11  http://opendata.muis.ee/media-list/621213      1
12  http://opendata.muis.ee/media-list/621214      1
13  http://opendata.muis.ee/media-list/621215      1
14  http://opendata.muis.ee/media-list/621216      1

Top 15 values for objects_sheet.object_url

                                 category  count
0   http://opendata.muis.ee/object/518063      1
1   http://opendata.muis.ee/object/621211      1
2   http://opendata.muis.ee/object/621203      1
3   http://opendata.muis.ee/object/621204      1
4   http://opendata.muis.ee/object/621206      1
5   http://opendata.muis.ee/object/621207      1
6   http://opendata.muis.ee/object/621208      1
7   http://opendata.muis.ee/object/621209      1
8   http://opendata.muis.ee/object/621210      1
9   http://opendata.muis.ee/object/621212      1
10  http://opendata.muis.ee/object/621201      1
11  http://opendata.muis.ee/object/621213      1
12  http://opendata.muis.ee/object/621214      1
13  http://opendata.muis.ee/object/621215      1
14  http://opendata.muis.ee/object/621216      1

Top 15 values for objects_sheet.title

           category  count
0           peapael    311
1              põll    257
2          käterätt    184
3      särk, naiste    172
4               nõu    168
5              särk    161
6             kleit    160
7          pealinik    153
8              korv    147
9               vöö    140
10         laudlina    106
11           viisud    100
12        kedervars     95
13           süstik     89
14  peakate, naiste     87

Top 15 values for objects_sheet.ethnic_group_name

   category  count
0   udmurdi   1661
1      mari   1519
2     vepsa   1074
3     isuri    966
4     handi    759
5   karjala    653
6    mordva    580
7      komi    568
8     liivi    549
9      ersa    420
10    soome    303
11   ungari    298
12    saami    261
13    vadja    232
14    mansi     87

Top 15 values for objects_sheet.collection_year

   category  count
0      1987    649
1      1989    626
2      1988    585
3      1983    563
4      1986    540
5      1975    539
6      1977    519
7      1990    366
8      1982    358
9      1937    354
10     1978    348
11     1976    344
12     1979    341
13     1981    311
14     1984    288

## Optional: One Specific Category Check

Use this cell to drill down into a specific column manually.

In [20]:
# Example:
# dfs['places']['country'].value_counts(dropna=True).head(20)
# dfs['materials']['material_category'].value_counts(dropna=True).head(20)